const json = (data, status = 200) => new Response(JSON.stringify(data, null, 2), { status, headers: { "content-type": "application/json; charset=utf-8" } });
function cleanUsername(v){return String(v||"").trim().replace(/[^\w.-]/g,"").slice(0,40)}
function b64url(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function makeId(username,token){const d=new TextEncoder().encode(`${username}:${token}`);const h=await crypto.subtle.digest("SHA-256",d);return b64url(new Uint8Array(h)).slice(0,24)}
async function verifyToken(token){const r=await fetch("https://api.cloudflare.com/client/v4/user/tokens/verify",{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)return {ok:false,reason:`Cloudflare HTTP ${r.status}`};const b=await r.json().catch(()=>null);return {ok:!!b?.success&&b?.result?.status==="active",status:b?.result?.status||"unknown"}}
export default {async fetch(request,env){const url=new URL(request.url);
 if(url.pathname==="/health")return json({ok:true,service:"RGB-Anti-filter",version:"0.2.0"});
 if(url.pathname==="/api/create"&&request.method==="POST"){try{const body=await request.json();const username=cleanUsername(body.username);const token=String(body.token||"").trim();if(!username)return json({ok:false,error:"Username is required."},400);if(!token)return json({ok:false,error:"Cloudflare API token is required."},400);if(token.length>512)return json({ok:false,error:"Token is too long."},400);const v=await verifyToken(token);if(!v.ok)return json({ok:false,error:"Cloudflare token is invalid, inactive, or could not be verified.",cloudflare_status:v.status},401);const id=await makeId(username,token);return json({ok:true,username,id,cloudflare_token:{verified:true,status:v.status},subscription_url:`${url.origin}/sub/${encodeURIComponent(id)}`,config_url:`${url.origin}/api/config/${encodeURIComponent(id)}`,note:"Prototype: token verification and stable links are working. A real proxy/node must be configured before the subscription contains a usable connection."});}catch{return json({ok:false,error:"Invalid JSON request."},400)}}
 if(url.pathname.startsWith("/sub/"))return new Response("# RGB-Anti-filter\n# Subscription endpoint is ready.\n# No proxy/node endpoint is configured yet.\n",{headers:{"content-type":"text/plain; charset=utf-8"}});
 if(url.pathname.startsWith("/api/config/"))return json({ok:true,ready:false,message:"Subscription generation endpoint is installed, but no real node is configured yet."});
 return env.ASSETS.fetch(request)}};
